/* TABLE XCHANNEL */

DROP TABLE XCHANNEL;
CREATE TABLE XCHANNEL(
        XCHANNEL_ID NUMBER NOT NULL,
        XCHANNEL_NAME VARCHAR2(50) NOT NULL,
        STORE_ID NUMBER NOT NULL,
        CREATETIME TIMESTAMP NOT NULL,
        AUTHOR NUMBER NOT NULL,
        LASTUPDATE TIMESTAMP NOT NULL,
        MARKFORDELETE NUMBER NOT NULL,
        SEQ NUMBER NOT NULL,
        TYPE VARCHAR2(2) NOT NULL,
        OPTCOUNTER NUMBER DEFAULT 0,
        PRIMARY KEY(XCHANNEL_ID),
        FOREIGN KEY(STORE_ID) REFERENCES STORE(STORE_ID),
        FOREIGN KEY(AUTHOR) REFERENCES USERS(USERS_ID)
);

/* SEQUENCE SEQ_XCHANNEL */

DROP SEQUENCE SEQ_XCHANNEL;
CREATE SEQUENCE SEQ_XCHANNEL MINVALUE 1 NOMAXVALUE START WITH 1 INCREMENT BY 1 NOCYCLE NOCACHE;

/* TABLE XGROUP */

DROP TABLE XGROUP;
CREATE TABLE XGROUP(
	XGROUP_ID NUMBER NOT NULL,
	XGROUP_NAME VARCHAR2(50) NOT NULL,
	DESCRIPTION VARCHAR2(256),
	LANGUAGE_ID NUMBER NOT NULL,
	STORE_ID NUMBER NOT NULL,
	OPTCOUNTER NUMBER DEFAULT 0,
	PRIMARY KEY(XGROUP_ID),
	FOREIGN KEY(LANGUAGE_ID) REFERENCES LANGUAGE(LANGUAGE_ID),
	FOREIGN KEY(STORE_ID) REFERENCES STORE(STORE_ID)
);

INSERT INTO XGROUP(XGROUP_ID) VALUES(1);
INSERT INTO XGROUP(XGROUP_ID) VALUES(2);
INSERT INTO XGROUP(XGROUP_ID) VALUES(3);

/* TABLE XUSERSGROUP */

DROP TABLE XUSERGROUP;
CREATE TABLE XUSERSGROUP(
	USERS_ID NUMBER NOT NULL,
	XGROUP_ID NUMBER NOT NULL,
	STORE_ID NUMBER NOT NULL,
	FOREIGN KEY(USERS_ID) REFERENCES USERS(USERS_ID),
	FOREIGN KEY(XGROUP_ID) REFERENCES XGROUP(XGROUP_ID),
	FOREIGN KEY(STORE_ID) REFERENCES STORE(STORE_ID)
);

/* TABLE XNRHISTORY */

DROP TABLE XNRHISTORY;
CREATE TABLE XNRHISTORY(
	XNRHISTORY_ID NUMBER NOT NULL,
	XNR_ID NUMBER NOT NULL,
	TYPE VARCHAR2(2) NOT NULL,
	CHECKER NUMBER NOT NULL,
	LASTUPDATE TIMESTAMP NOT NULL,
	STATUS VARCHAR2(2) NOT NULL,
	XCOMMENT VARCHAR2(256),
	PRIMARY KEY(XNRHISTORY_ID),
	FOREIGN KEY(CHECKER) REFERENCES USERS(USERS_ID)
);

/* SEQUENCE SEQ_XNRHISTORY */
DROP SEQUENCE SEQ_XNRHISTORY;
CREATE SEQUENCE SEQ_XNRHISTORY MINVALUE 1 NOMAXVALUE START WITH 1 INCREMENT BY 1 NOCYCLE NOCACHE;

/* TABLE NEWS */
DROP TABLE XNEWS;
CREATE TABLE XNEWS(
	XNEWS_ID NUMBER NOT NULL,
	TITLE VARCHAR2(100) NOT NULL,
	FIRSTIMAGE VARCHAR2(256),
	SUMMARY VARCHAR2(512),
	DETAILS CLOB NOT NULL,
	CREATETIME TIMESTAMP NOT NULL,
	AUTHOR NUMBER NOT NULL,
	XCHANNEL_ID NUMBER NOT NULL,
	SEQ NUMBER NOT NULL,
	XGROUP_ID VARCHAR2(256) NOT NULL,
	STATUS VARCHAR2(2) NOT NULL,
	FIELD1 NUMBER,
	FIELD2 VARCHAR2(50),
	FIELD3 TIMESTAMP,
	OPTCOUNTER NUMBER DEFAULT 0,
	PRIMARY KEY(XNEWS_ID),
	FOREIGN KEY(AUTHOR) REFERENCES USERS(USERS_ID),
	FOREIGN KEY(XCHANNEL_ID) REFERENCES XCHANNEL(XCHANNEL_ID)
);

/* SEQUENCE SEQ_XNEWS */
DROP SEQUENCE SEQ_XNEWS;
CREATE SEQUENCE SEQ_XNEWS MINVALUE 1 NOMAXVALUE START WITH 1 INCREMENT BY 1 NOCYCLE NOCACHE;

/* TABLE XREFERENCES */

DROP TABLE XREFERENCES;
CREATE TABLE XREFERENCES(
	XREFERENCES_ID NUMBER NOT NULL,
	SERIALNUMBER VARCHAR2(32) NOT NULL,
	COUNTRY VARCHAR2(32) NOT NULL,
	PROJECTPLACE VARCHAR2(128) NOT NULL,
	DESCRIPTION CLOB NOT NULL,
	TYPE VARCHAR2(32) NOT NULL,
	INSTALLTIME VARCHAR2(32) NOT NULL,
	INSTALLSERIES VARCHAR2(128) NOT NULL,
	INSTALLDETAILS VARCHAR2(256) NOT NULL,
	TOTALCAPACITY VARCHAR(16) NOT NULL,
	KEYCAPACITY VARCHAR2(2000) NOT NULL,
	PICTURES VARCHAR2(512),
	CREATETIME TIMESTAMP NOT NULL,
	AUTHOR NUMBER NOT NULL,
	XCHANNEL_ID NUMBER NOT NULL,
	SEQ NUMBER NOT NULL,
	XGROUP_ID VARCHAR2(256) NOT NULL,
	CATGROUP_ID NUMBER NOT NULL,
	STATUS VARCHAR2(2) NOT NULL,
	FIELD1 NUMBER,
	FIELD2 VARCHAR2(50),
	FIELD3 TIMESTAMP,
	OPTCOUNTER NUMBER DEFAULT 0,	
	PRIMARY KEY(XREFERENCES_ID),
	FOREIGN KEY(AUTHOR) REFERENCES USERS(USERS_ID),
	FOREIGN KEY(XCHANNEL_ID) REFERENCES XCHANNEL(XCHANNEL_ID),
	FOREIGN KEY(CATGROUP_ID) REFERENCES CATGROUP(CATGROUP_ID)
);

DROP SEQUENCE SEQ_XREFERENCES;
CREATE SEQUENCE SEQ_XREFERENCES MINVALUE 1 NOMAXVALUE START WITH 1 INCREMENT BY 1 NOCYCLE NOCACHE;


/* TABLE X_ESPOT */

DROP TABLE X_ESPOT;
CREATE TABLE X_ESPOT(
        ESPOT_ID NUMBER NOT NULL,
        TEMPLATE CLOB,
        TYPE NUMBER,
        PRIORITY NUMBER,
        FILE_ID NUMBER,
        USAGE VARCHAR2(50),
        PRIMARY KEY(ESPOT_ID)
);

/* TABLE W_FTP */
INSERT INTO W_FTP(ID, HOST, PORT, USERNAME, PASSWORD, XPATH, TYPE) VALUES(3, '10.176.0.40', '21', 'root', 'passw0rd','/opt/IBM/HTTPServer/conf/web/channel/news/images', '3');
INSERT INTO W_FTP(ID, HOST, PORT, USERNAME, PASSWORD, XPATH, TYPE) VALUES(4, '10.176.0.40', '21', 'root', 'passw0rd','/opt/IBM/HTTPServer/conf/web/channel/references/images', '4');

