DROP TABLE IF EXISTS STORE;
CREATE TABLE `STORE` (
  `STORE_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CREATETIME` datetime NOT NULL,
  `NAME` varchar(255) NOT NULL,
  PRIMARY KEY (`STORE_ID`),
  UNIQUE KEY `NAME` (`NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS ATTR;
CREATE TABLE `ATTR` (
  `ATTR_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CREATETIME` datetime NOT NULL,
  `DESCRIPTION` varchar(100) DEFAULT '',
  `DISPLAYABLE` int(11) DEFAULT 1,
  `NAME` varchar(255) NOT NULL,
  `SEQUENCE` int(11) DEFAULT 0,
  `ATTRTYPE_ID` int(11) DEFAULT 1,
  `ATTRUSAGE` int(11) NOT NULL,
  `STORE_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`ATTR_ID`),
  KEY `FK1ED1F1A70017D` (`STORE_ID`),
  CONSTRAINT `attr_ibfk_1` FOREIGN KEY (`STORE_ID`) REFERENCES `STORE` (`STORE_ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS ATTRVAL;
CREATE TABLE `ATTRVAL` (
  `ATTRVAL_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CREATETIME` datetime NOT NULL,
  `LASTUPDATE` datetime NOT NULL,
  `VALUE` varchar(100) NOT NULL,
  `ATTR_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`ATTRVAL_ID`),
  KEY `FK2926770A6910EA8` (`ATTR_ID`),
  CONSTRAINT `attrval_ibfk_1` FOREIGN KEY (`ATTR_ID`) REFERENCES `ATTR` (`ATTR_ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS CATENTRY;
CREATE TABLE `CATENTRY` (
  `CATENTRY_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CREATETIME` datetime NOT NULL,
  `LASTUPDATE` datetime NOT NULL,
  `PARTNUMBER` varchar(255) NOT NULL,
  `TYPE` int(11) NOT NULL,
  PRIMARY KEY (`CATENTRY_ID`),
  UNIQUE KEY `PARTNUMBER` (`PARTNUMBER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



DROP TABLE IF EXISTS CATENTDESC;
CREATE TABLE `CATENTDESC` (
  `CATENTRY_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `LONGDESCRIPTION` blob,
  `NAME` varchar(255) NOT NULL,
  `SHORTDESCRIPTION` varchar(255) DEFAULT '',
  PRIMARY KEY (`CATENTRY_ID`),
  KEY `FK76632966503D98F4` (`CATENTRY_ID`),
  CONSTRAINT `catentdesc_ibfk_1` FOREIGN KEY (`CATENTRY_ID`) REFERENCES `CATENTRY` (`CATENTRY_ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS CATENTATTR;
CREATE TABLE `CATENTATTR` (
  `CATENTRY_ID` bigint(20) NOT NULL,
  `ATTRVAL_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`CATENTRY_ID`,`ATTRVAL_ID`),
  KEY `FK8334324DA80B3F40` (`ATTRVAL_ID`),
  KEY `FK8334324D503D98F4` (`CATENTRY_ID`),
  CONSTRAINT `catentryattr_ibfk_1` FOREIGN KEY (`CATENTRY_ID`) REFERENCES `CATENTRY` (`CATENTRY_ID`) ON DELETE CASCADE,
  CONSTRAINT `catentryattr_ibfk_2` FOREIGN KEY (`ATTRVAL_ID`) REFERENCES `ATTRVAL` (`ATTRVAL_ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



DROP TABLE IF EXISTS STORECENT;
CREATE TABLE `STORECENT` (
  `CATENTRY_ID` bigint(20) NOT NULL,
  `STORE_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`CATENTRY_ID`,`STORE_ID`),
  KEY `FKAF839E9503D98F4` (`CATENTRY_ID`),
  KEY `FKAF839E9A70017D` (`STORE_ID`),
  CONSTRAINT `storecent_ibfk_1` FOREIGN KEY (`STORE_ID`) REFERENCES `STORE` (`STORE_ID`) ON DELETE CASCADE,
  CONSTRAINT `storecent_ibfk_2` FOREIGN KEY (`CATENTRY_ID`) REFERENCES `CATENTRY` (`CATENTRY_ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



DROP TABLE IF EXISTS USERS;
CREATE TABLE `USERS` (
  `USER_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CREATETIME` datetime NOT NULL,
  `EMAIL` varchar(80) NOT NULL,
  `LASTUPDATE` datetime NOT NULL,
  `PASSWORD` varchar(100) DEFAULT '',
  `STATUS` int(11) DEFAULT 1,
  `USERNAME` varchar(80) NOT NULL,
  `STORE_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`USER_ID`),
  UNIQUE KEY `USERNAME` (`USERNAME`),
  KEY `FK4D495E8A70017D` (`STORE_ID`),
  CONSTRAINT `users_ibfk_1` FOREIGN KEY (`STORE_ID`) REFERENCES `STORE` (`STORE_ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

